name: Compile LaTeX Documents

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up LaTeX environment
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          lectures.tex
          classes.tex
        working_directory: LaTeX
        args: -interaction=nonstopmode -file-line-error
        extra_system_packages: "biber"
        texlive_package: "texlive-pdftex"
        
    - name: Create output directory
      run: |
        mkdir -p compiled_pdfs
        cp LaTeX/*.pdf compiled_pdfs/ || true
        
    - name: List generated files
      run: |
        ls -la LaTeX/
        ls -la compiled_pdfs/ || echo "No PDF files found in compiled_pdfs"
        
    - name: Upload compiled PDFs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdfs
        path: compiled_pdfs/